services:
  web:
    image: php:8.2-apache    #check the php version you need for your project
    ports:
      - "84:80"    #this line maps your pc port to the container port
    depends_on:
      - db    #this line links this container to the db container
    volumes:
      - ./html:/var/www/html    #this line maps the content of ./html in your pc to the /var/www/html of the container
    networks: 
      - demo
  db:
    image: mysql:8.1.0    #check the mysql version you need for your project
    environment:
      MYSQL_ROOT_PASSWORD: root_password    #you can change the mysql root password here
      MYSQL_DATABASE: lamp_db    #you can change the database name here
    volumes:
      - ./mysql_data:/var/lib/mysql    #this line maps the content of ./mysql_data in your pc to the /var/lib/mysql of the container
    networks: 
      - demo
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "85:80"    #this line maps your pc port to the container port
    depends_on:
      - db    #this line links this container to the db container
    environment:
      PMA_HOST: db
    networks: 
      - demo
networks: 
  demo: 
    driver: bridge 
    name: demo 
    external: true 