---
# cluster_name is used to group the nodes in a folder within VirtualBox:
cluster_name: ansible
network:
  control_ip: 192.168.56.180
nodes:
  control:
    cpu: 4
    memory: 4096
  workers:
    count: 2
    cpu: 2
    memory: 2048
software:
  box: bento/ubuntu-24.04
  calico: 3.26.0
  os: xUbuntu_24.04
