apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lamp-apache-pv-claim
  labels:
    app: lamp-apache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
