FROM ubuntu
#ENTRYPOINT ["/bin/echo"] 
#ENTRYPOINT ["/bin/bash"] 

# use below line to pass args. In this case it's Hello World as default value
#applicable when Entrypoint is echo  
#CMD ["Hello, World"]
CMD ["/usr/bin/ls","-la"]
